Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2023-07, with the labels that each got.

#14 Add GitHub Actions
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
Labels: enhancement, docker, actions

#16 Update to new namespace
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
  README.md
Labels: docker, actions

#17 Fix last remaining namespace difference
  README.md
Labels: documentation

#18 Allow codeql to be run manually
  .github/workflows/codeql.yml
Labels: actions

#19 Update Dev Container to correct tags
  .devcontainer/devcontainer.json
Labels: docker

#20 Switch to Single File Examples
  examples/OpenCV/TagGenerator.hpp
  examples/OpenCV/Tag_Generator.h
  src/main.cpp
Labels: formatting

#25 Add Funding Links to GitHub
  .github/FUNDING.yml
Labels: github

#27 Update docker_jetpack.yml
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
Labels: github

#22 Auto Build Executables on Tag Creation
  .devcontainer/Dockerfile_JetPack
  .devcontainer/devcontainer.json
  .devcontainer/start.sh
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  CMakeLists.txt
  README.md
Labels: enhancement, docker, actions

#28 Remove start script
  .devcontainer/start.sh
Labels: cleanup

#35 Add CONTRIBUTING.md
  .github/workflows/codeql.yml
  .gitignore
  CONTRIBUTING.md
Labels: documentation, github

#36 Add Contributing Docs to Navigation
  CONTRIBUTING.md
  Doxyfile
  data/README.md
  docs/Doxygen/resources/DoxygenLayout.xml
  docs/README.md
  examples/README.md
  external/README.md
  src/README.md
  src/algorithms/README.md
  src/interfaces/README.md
  src/states/README.md
  src/util/README.md
  src/vision/README.md
  tests/README.md
  tools/README.md
  tools/valgrind/README.md
Labels: documentation, formatting, github, cleanup

#37 Fix link typo
  CONTRIBUTING.md
Labels: bug, documentation

#38 Upgrade OpenCV
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
Labels: docker

#39 Disable Automatic Running of Docker Builders
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
Labels: actions

#40 Add GDB to JetPack Image
  .devcontainer/Dockerfile_JetPack
  .devcontainer/devcontainer.json
  .github/workflows/deploy_autonomy.yml
Labels: docker

#41 Add CLion Configuration
  .idea/cmake.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/runConfigurations/Autonomy_Software.xml
Labels: formatting, github

#42 Remove CLion Configs
  .gitignore
  .idea/cmake.xml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/runConfigurations/Autonomy_Software.xml
Labels: formatting, github, cleanup

#45 Rename CMake installer
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/install-cmake.sh
Labels: github, cleanup

#46 Add Google Test Framework
  CMakeLists.txt
  tests/Example.cc
  tests/Integration/README.md
  tests/Unit/README.md
Labels: enhancement, tests

#47 Added Documentation to Tests
  CMakeLists.txt
  tests/Example.cc
  tests/Integration/main.cc
  tests/Unit/main.cc
Labels: tests

#50 Update GitHub Actions
  .github/workflows/codeql.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  .gitignore
  tools/valgrind/run_valgrind.sh
Labels: actions, unit tests

#53 Update Spelling and Capitalization to meet MRDT Brand Guide
  README.md
  data/README.md
  docs/README.md
  examples/README.md
  external/README.md
  src/README.md
  src/interfaces/README.md
  src/states/README.md
  src/util/ASCII/README.md
  src/util/README.md
  src/vision/README.md
  tests/Integration/README.md
  tests/README.md
  tests/Unit/README.md
  tools/README.md
Labels: documentation, formatting

#54 Add Vertical Column 20 to left of max line length
  .devcontainer/devcontainer.json
Labels: enhancement, dev-environment

#60 Elegant Example Running
  examples/README.md
  examples/threading/ArucoGenerateTags.hpp
  examples/threading/PrimeNumbers.hpp
  src/main.cpp
  src/util/ExampleChecker.h
Labels: enhancement, 2-Star

#58 Implement Multi-Threading into the Codebase
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/devcontainer.json
  CMakeLists.txt
  CONTRIBUTING.md
  data/ASCII/README.md
  data/ASCII/v24.txt
  examples/README.md
  examples/opencv/TagGenerator.hpp
  examples/threading/ArucoGenerateTags.hpp
  examples/threading/PrimeNumbers.hpp
  external/README.md
  external/threadpool/BSThreadPool.hpp
  external/threadpool/README.md
  src/AutonomyGlobals.h
  src/README.md
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/drivers/README.md
  src/interfaces/AutonomyThread.hpp
  src/interfaces/README.md
  src/main.cpp
  src/threads/README.md
  src/util/ExampleChecker.h
Labels: enhancement, 5-Star

#63 Setup debugging in container environment.
  .devcontainer/devcontainer.json
  Doxyfile
  README.md
  data/README_Resources/README.md
  data/README_Resources/images/breakpoint_selection.png
  data/README_Resources/images/kit_selection_first_container_start.png
  data/README_Resources/images/kit_selection_toolbar.png
  data/README_Resources/images/toolbar_build_run.png
  data/README_Resources/images/toolbar_cmake_debug_config.png
  data/README_Resources/images/toolbar_debug_button.png
  data/README_Resources/images/vscode_debug_mode.png
  src/main.cpp
  src/threads/README.md
Labels: 1-Star, dev-environment

#64 Update README.md
  README.md
Labels: bug, documentation
