Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2023-08, with the labels that each got.

#66 Initial State Machine Implementation
  CMakeLists.txt
  src/AutonomyConstants.h
  src/AutonomyGlobals.h
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/interfaces/StateMachine.hpp
  src/main.cpp
  src/states/AbortState.hpp
  src/states/ApproachingGateState.hpp
  src/states/ApproachingMarkerState.hpp
  src/states/AvoidanceState.hpp
  src/states/IdleState.hpp
  src/states/NavigationState.hpp
  src/states/ReverseState.hpp
  src/states/SearchPatternState.hpp
  src/states/StuckState.hpp
Labels: enhancement, 5-Star

#65 Added step-by-step setup guide to main README Getting Started section
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/devcontainer.json
  README.md
  data/README_Resources/images/vscode_install_extensions.png
  docs/README.md
Labels: documentation, 1-Star, dev-environment

#75 Update Packages
  .devcontainer/Dockerfile_JetPack
  .devcontainer/Dockerfile_Ubuntu
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  src/AutonomyGlobals.cpp
Labels: enhancement, docker

#82 [HOTFIX] Limit when documentation is updated.
  .github/workflows/doxygen_generate.yml
Labels: bug, actions

#81 Add header block to project README
  .gitignore
  README.md
Labels: documentation, 1-Star, formatting

#84 Fix position of description
  README.md
Labels: bug, documentation, formatting

#85 Switch to OS Version Numbered Packages
  .devcontainer/Dockerfile_JetPack5
  .devcontainer/Dockerfile_Ubuntu20
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  tools/docker/increment_jetpack.sh
  tools/docker/increment_ubuntu.sh
Labels: 1-Star, formatting, docker, actions, cleanup, dev-environment

#86 Fixing names of docker images
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  README.md
Labels: bug, 1-Star, formatting, docker, actions, cleanup, dev-environment

#87 Limit what calls Doxygen and file action reference to docs tile on README
  .github/workflows/doxygen_generate.yml
  README.md
Labels: bug, 1-Star, formatting, actions

#88 Limit what calls Doxygen and file action reference to docs tile on README
  .github/workflows/doxygen_generate.yml
Labels: bug, 1-Star, formatting, actions

#89 Add Cowsay Feature for Enhanced Developer Morale 🐄🌈
  .devcontainer/Dockerfile_Ubuntu20
  .devcontainer/devcontainer.json
  data/Cowsay_Cows/README.md
  data/Cowsay_Cows/apt.cow
  data/Cowsay_Cows/cower.cow
  data/Cowsay_Cows/default.cow
  data/Cowsay_Cows/dragon-and-cow.cow
  data/Cowsay_Cows/moofasa.cow
  data/Cowsay_Cows/skeleton.cow
  data/Cowsay_Cows/swoosh.cow
  data/Cowsay_Cows/three-eyes.cow
  data/Cowsay_Cows/tux.cow
  data/Cowsay_Cows/vader.cow
  data/Cowsay_Cows/www.cow
  tools/toggle_cowsay.sh
Labels: enhancement, 1-Star, dev-environment

#91 General README Updates
  data/README_Resources/README.md
  data/README_Resources/images/state_machine_diagram.png
  src/states/README.md
Labels: documentation, enhancement, 1-Star

#94 Add "duplicate" image reference
  src/states/README.md
Labels: bug, documentation, 1-Star

#93 General Action Upgrades
  .github/workflows/codeql.yml
  .github/workflows/docker_jetpack.yml
  .github/workflows/docker_ubuntu.yml
Labels: bug, 1-Star, docker, actions

#95 Allow to have queue of codeql
  .github/workflows/codeql.yml
Labels: bug, enhancement, 1-Star, actions

#96 Update Docker Image Names and Version Numbers
  README.md
Labels: bug, documentation, 1-Star, docker

#97 Cowsay Bug and Removed Docker Extension
  .devcontainer/Dockerfile_Ubuntu20
  .devcontainer/devcontainer.json
Labels: bug, docker

#99 Update Docker Image Names Again...
  .devcontainer/Dockerfile_Focal
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  .devcontainer/devcontainer.json
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  README.md
Labels: 1-Star, docker, actions, cleanup, dev-environment

#90 Multithreading Interface Documentation
  README.md
  examples/threading/ArucoGenerateTags.hpp
  src/AutonomyConstants.h
  src/interfaces/AutonomyThread.hpp
  src/threads/README.md
Labels: documentation, 1-Star

#100 Set Up Codeowners
  .github/CODEOWNERS
Labels: 1-Star, cleanup

#101 Add Logo and Fix Build Type
  CMakeLists.txt
  data/CPACK/logo.ico
Labels: bug, 1-Star, actions

#102 *** Iterate Versions ***
  .devcontainer/Dockerfile_Focal
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  CMakeLists.txt
  Doxyfile
  src/IdentitySoftware.h
Labels: enhancement, 1-Star, formatting, docker

#103 Shorten Release Names
  .github/workflows/deploy_autonomy.yml
Labels: bug, 1-Star, actions

#106 Fix Copyright Organization Name
  .devcontainer/devcontainer.json
  examples/opencv/TagGenerator.hpp
  examples/threading/ArucoGenerateTags.hpp
  examples/threading/PrimeNumbers.hpp
  src/AutonomyConstants.h
  src/AutonomyGlobals.cpp
  src/AutonomyGlobals.h
  src/IdentitySoftware.cpp
  src/IdentitySoftware.h
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/interfaces/AutonomyThread.hpp
  src/interfaces/StateMachine.hpp
  src/main.cpp
  src/states/AbortState.hpp
  src/states/ApproachingGateState.hpp
  src/states/ApproachingMarkerState.hpp
  src/states/AvoidanceState.hpp
  src/states/IdleState.hpp
  src/states/NavigationState.hpp
  src/states/ReverseState.hpp
  src/states/SearchPatternState.hpp
  src/states/StuckState.hpp
  src/util/ExampleChecker.h
  src/util/NumberOperations.hpp
  tests/Example.cc
  tests/Integration/main.cc
  tests/Unit/main.cc
Labels: bug, documentation, 1-Star, cleanup

#107 Logging Improvements
  CMakeLists.txt
  src/AutonomyGlobals.cpp
  src/AutonomyGlobals.h
  src/AutonomyLogging.h
  src/drivers/DriveBoard.cpp
  src/drivers/MultimediaBoard.cpp
  src/drivers/NavigationBoard.cpp
  src/interfaces/StateMachine.hpp
  src/main.cpp
  src/states/AbortState.hpp
  src/states/ApproachingGateState.hpp
  src/states/ApproachingMarkerState.hpp
  src/states/AvoidanceState.hpp
  src/states/IdleState.hpp
  src/states/NavigationState.hpp
  src/states/ReverseState.hpp
  src/states/SearchPatternState.hpp
  src/states/StuckState.hpp
Labels: enhancement, 1-Star, formatting, cleanup, logging

#109 Add gruntfuggly.todo-tree extension to environment
  .devcontainer/devcontainer.json
Labels: enhancement, 1-Star, dev-environment

#108 Fix Project Warnings
  .devcontainer/devcontainer.json
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
Labels: 1-Star, formatting, cleanup
