Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2023-09, with the labels that each got.

#111 [BUG] Examples Runner
  src/main.cpp
Labels: bug, 1-Star

#114 Remove all warnings from application
  src/states/AbortState.hpp
  src/states/ApproachingGateState.hpp
  src/states/ApproachingMarkerState.hpp
  src/states/AvoidanceState.hpp
  src/states/IdleState.hpp
  src/states/NavigationState.hpp
  src/states/ReverseState.hpp
  src/states/SearchPatternState.hpp
  src/states/StuckState.hpp
Labels: enhancement, 1-Star, formatting, cleanup, dev-environment

#115 Add clang-format Check to Action Suite
  .clang-format
  .github/workflows/clang_check.yml
  src/states/ApproachingGateState.hpp
  src/states/AvoidanceState.hpp
  src/states/IdleState.hpp
  src/states/NavigationState.hpp
  src/states/ReverseState.hpp
  src/states/SearchPatternState.hpp
Labels: enhancement, 1-Star, actions

#116 Add Concurrency Flag
  .github/workflows/clang_check.yml
  README.md
Labels: bug, 1-Star, actions

#113 Fix `make install` breaks during link to RoveComm
  CMakeLists.txt
Labels: bug, 1-Star, rovecomm

#118 Add Install Doc Page to Doxygen Site
  CONTRIBUTING.md
  INSTALL.md
  README.md
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: documentation, enhancement, 1-Star

#119 Fix Doxygen Comment Blocks are based off of Eastern Time
  .devcontainer/Dockerfile_Focal
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  CONTRIBUTING.md
  INSTALL.md
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: bug, 1-Star, docker, dev-environment

#120 Cowsay Improvements
  data/Cowsay_Cows/icarus.cow
  data/Cowsay_Cows/swoosh.cow
Labels: enhancement, 1-Star, formatting, dev-environment

#121 Seperate Debug Seteps and Increment Docker Versions
  DEBUG.md
  README.md
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: documentation, enhancement, 1-Star, formatting

#126 Setup Self Hosted Runners
  .github/workflows/clang_check.yml
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/doxygen_generate.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  .gitignore
  CMakeLists.txt
  tools/action-runners/Dockerfile_Jammy
  tools/action-runners/Dockerfile_JetPack
  tools/action-runners/scripts/start.sh
Labels: bug, 3-Star, docker, actions, dev-environment

#128 Fix Doxygen
  .github/workflows/doxygen_generate.yml
Labels: bug, 1-Star, actions

#129 Add Template for Compose without Tokens
  tools/action-runners/compose.yml
Labels: bug, 1-Star, docker, actions, dev-environment

#131 Add Return to GitHub
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: documentation, 1-Star

#132 Hotfix/jetson testing
  .devcontainer/devcontainer.json
  .gitignore
  CMakeLists.txt
  src/AutonomyConstants.h
Labels: enhancement, 1-Star, dev-environment
