Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-08, with the labels that each got.

#270 Final Updates from URC 2024
  README.md
  src/AutonomyConstants.h
  src/AutonomyLogging.cpp
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/handlers/StateMachineHandler.cpp
  src/handlers/StateMachineHandler.h
  src/handlers/WaypointHandler.cpp
  src/handlers/WaypointHandler.h
  src/interfaces/State.hpp
  src/states/ApproachingMarkerState.cpp
  src/states/AvoidanceState.cpp
  src/states/IdleState.cpp
  src/states/NavigatingState.cpp
  src/states/VerifyingMarkerState.cpp
  src/states/VerifyingObjectState.cpp
  src/states/VerifyingPositionState.cpp
  src/states/VerifyingPositionState.h
Labels: bug, enhancement, 5-Star, formatting, cleanup, dev-environment, rovecomm, logging, cameras, state-machine

#269 Add Unit Testing to ARM64
  .github/workflows/tests.yml
  tools/action-runners/Dockerfile_Jammy
  tools/action-runners/Dockerfile_JetPack
Labels: enhancement, 1-Star, actions, unit tests

#271 Restrict Permissions for High-Resource GitHub Actions: Deploy Autonomy & Rebuild Docker
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/deploy_docker.yml
Labels: 1-Star, actions

#277 [HOTFIX] Deploying Autonomy and CodeQL Timeouts
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
Labels: bug, 4-Star, actions

#272 Cleanup and fix compile warning.
  src/drivers/MultimediaBoard.cpp
  src/drivers/NavigationBoard.cpp
  src/handlers/StateMachineHandler.cpp
  src/handlers/StateMachineHandler.h
  src/states/ApproachingMarkerState.cpp
  src/states/IdleState.cpp
  src/states/NavigatingState.cpp
  src/states/VerifyingMarkerState.cpp
  src/states/VerifyingObjectState.cpp
  src/states/VerifyingPositionState.cpp
Labels: cleanup

#268 Add extension
  .devcontainer/devcontainer.json
Labels: dev-environment

#281 Fix Time Function in Logging
  src/AutonomyLogging.cpp
Labels: bug, enhancement, 1-Star, formatting

#283 Fix Intellisense Workspace Scan Crash
  .devcontainer/devcontainer.json
Labels: bug, dev-environment

#284 Action Updates
  .github/workflows/codeql.yml
  .github/workflows/help_request.yml
  .github/workflows/tests.yml
Labels: enhancement, 1-Star, actions

#266 Log Playback and Visualization
  src/AutonomyLogging.cpp
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
  src/handlers/CameraHandler.cpp
  src/handlers/CameraHandler.h
  src/handlers/ObjectDetectionHandler.cpp
  src/handlers/ObjectDetectionHandler.h
  src/handlers/RecordingHandler.cpp
  src/handlers/RecordingHandler.h
  src/handlers/StateMachineHandler.cpp
  src/handlers/TagDetectionHandler.cpp
  src/handlers/TagDetectionHandler.h
  src/handlers/WaypointHandler.cpp
  src/interfaces/AutonomyThread.hpp
  src/main.cpp
  src/states/StuckState.cpp
  src/states/StuckState.h
  src/states/VerifyingPositionState.cpp
  src/util/vision/FetchContainers.hpp
  src/vision/aruco/TagDetector.cpp
  src/vision/cameras/BasicCam.cpp
  src/vision/cameras/ZEDCam.cpp
  src/vision/cameras/sim/SIMBasicCam.cpp
  src/vision/objects/ObjectDetector.cpp
  tools/logging/log_playback.py
Labels: 1-Star, logging

#285 Create SECURITY.md
  SECURITY.md
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  tools/action-runners/Dockerfile_Jammy
  tools/action-runners/Dockerfile_JetPack
  tools/action-runners/docker-compose.yml
Labels: documentation, enhancement, 1-Star

#287 Tag Detection Tweaks and State Machine Bug Fixes
  src/drivers/MultimediaBoard.cpp
  src/states/ApproachingMarkerState.cpp
  src/states/ApproachingMarkerState.h
  src/states/ApproachingObjectState.cpp
  src/states/NavigatingState.cpp
  src/states/NavigatingState.h
  src/states/SearchPatternState.cpp
  src/states/VerifyingMarkerState.cpp
  src/states/VerifyingObjectState.cpp
  src/vision/aruco/TagDetector.cpp
  src/vision/aruco/TagDetector.h
Labels: bug, 1-Star, state-machine, tag-detection

#288 Competition Year 2025 Setup
  data/ASCII/v25.txt
  src/main.cpp
Labels: documentation, enhancement, 1-Star, formatting

#303 Add Code Coverage Checking to CI Pipeline
  .github/workflows/coverage.yml
  CMakeLists.txt
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
Labels: enhancement, 2-Star, actions, testing

#301 Add Code of Conduct, PR & Issue Templates to Improve Workflow
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/package_upgrade.yml
  .github/ISSUE_TEMPLATE/research_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/coverage.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  DEBUG.md
  INSTALL.md
  README.md
  SECURITY.md
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: enhancement, 1-Star, formatting

#300 Add Help Requester Action
  .github/workflows/help_requester.yml
  tools/help-request/extract_comments.sh
  tools/help-request/send_discord.sh
Labels: enhancement, 2-Star, actions

#304 Hotfix: Fix tests.yml Variable Passing and Restore CMAKE Project Version
  .github/workflows/tests.yml
  CMakeLists.txt
Labels: bug, 1-Star, actions, testing, dev-environment
