Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-09, with the labels that each got.

#309 Fix: Missing .deepsource.toml in Default Branch
  .deepsource.toml
  README.md
Labels: bug, enhancement, 1-Star, formatting, actions, testing, security

#315 Fix what checks are used in deepsource
  .deepsource.toml
  .github/workflows/coverage.yml
Labels: bug, 1-Star, actions

#316 Specify Number of Parallel Jobs in CMake Extention
  .devcontainer/devcontainer.json
  README.md
Labels: enhancement, 1-Star, dev-environment

#318 Remove Unfinished Navboard Simulator
  tools/navboard-simulation/run.py
Labels: 1-Star, cleanup

#320 Update Quill to 7.1.0
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  README.md
  src/AutonomyLogging.h
  tools/package-builders/quill/quill-amd64-pkg.sh
  tools/package-builders/quill/quill-arm64-pkg.sh
Labels: 1-Star, formatting, logging, upgrade

#321 [CRITICAL FIX] All Unit/Integration Tests Skipped
  .github/workflows/tests.yml
Labels: bug, 1-Star, actions, testing

#322 [CRITICAL FIX] All Unit/Integration Tests Skipped (cont.)
  .github/workflows/tests.yml
Labels: bug, 1-Star, actions, testing

#259 Implement A-Star
  src/AutonomyConstants.h
  src/AutonomyLogging.cpp
  src/algorithms/controllers/StanleyController.cpp
  src/algorithms/controllers/StanleyController.h
  src/algorithms/planners/AStar.cpp
  src/algorithms/planners/AStar.h
  src/states/AvoidanceState.cpp
  src/states/AvoidanceState.h
  src/states/ReversingState.cpp
  src/util/planners/Nodes.hpp
  src/vision/aruco/ArucoDetection.hpp
  tests/Unit/src/algorithms/pathplanners/AStarPlanner.cc
Labels: enhancement, 3-Star, testing, state-machine

#267 Implement SVO recording for ZED Cameras
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/vision/cameras/ZEDCam.cpp
  src/vision/cameras/ZEDCam.h
Labels: enhancement, 1-Star, logging, cameras

#324 Update .deepsource.toml
  .deepsource.toml
Labels: enhancement, 1-Star, actions
