Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-10, with the labels that each got.

#325 Update Test Coverage Destinations
  .deepsource.toml
  .github/workflows/coverage.yml
Labels: enhancement, 1-Star, actions, testing

#328 Update Quill Logging Library
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  README.md
  tools/package-builders/quill/quill-amd64-pkg.sh
  tools/package-builders/quill/quill-arm64-pkg.sh
Labels: enhancement, 1-Star, logging, upgrade

#327 Update README.md
  README.md
Labels: bug, 1-Star, actions, dev-environment

#329 Implement LOG_NOTICE from New Quill Version
  src/AutonomyConstants.h
  src/drivers/NavigationBoard.cpp
  src/handlers/StateMachineHandler.cpp
  src/handlers/WaypointHandler.cpp
  src/states/IdleState.cpp
  src/states/NavigatingState.cpp
  src/states/ReversingState.cpp
  src/states/SearchPatternState.cpp
  src/states/StuckState.cpp
  src/vision/cameras/ZEDCam.cpp
Labels: enhancement, logging

#330 Add Useful Packages
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
Labels: enhancement, 1-Star, dev-environment

#332 Fix and Improve Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/enhancement_request.yml
  .github/ISSUE_TEMPLATE/package_upgrade.yml
  .github/ISSUE_TEMPLATE/research_request.yml
Labels: bug, enhancement, 1-Star, formatting
