Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-04, with the labels that each got.

#229 Update TODO Tree extension settings and highlights
  .devcontainer/devcontainer.json
  CONTRIBUTING.md
Labels: documentation, enhancement, 1-Star, formatting, dev-environment

#230 Update/Merge StateMachine with Development
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/algorithms/DifferentialDrive.hpp
  src/algorithms/SearchPattern.hpp
  src/algorithms/controllers/PIDController.cpp
  src/drivers/DriveBoard.cpp
  src/handlers/StateMachineHandler.cpp
  src/handlers/StateMachineHandler.h
  src/handlers/WaypointHandler.h
  src/interfaces/State.hpp
  src/states/ApproachingMarkerState.cpp
  src/states/ApproachingMarkerState.h
  src/states/IdleState.cpp
  src/states/IdleState.h
  src/states/NavigatingState.cpp
  src/states/ReversingState.cpp
  src/states/ReversingState.h
  src/states/SearchPatternState.cpp
  src/states/SearchPatternState.h
  src/states/StuckState.cpp
  src/states/StuckState.h
  src/util/NumberOperations.hpp
  src/util/vision/TagDetectionUtilty.hpp
  src/vision/aruco/TagDetector.cpp
  src/vision/aruco/TensorflowTagDetection.hpp
  tests/Unit/src/algorithms/SearchPattern.cc
  tests/Unit/src/util/NumberOperations.cc
Labels: enhancement, rovecomm, logging, state-machine

#235 Reconfigure Camera Layout and Add Battery Voltage Monitoring
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  examples/vision/cameras/OpenBasicCam.hpp
  examples/vision/dnn/InferenceYOLOModel.hpp
  examples/vision/tagdetection/ArucoDetectionBasicCam.hpp
  src/AutonomyConstants.h
  src/handlers/CameraHandler.cpp
  src/handlers/CameraHandler.h
  src/handlers/ObjectDetectionHandler.cpp
  src/handlers/ObjectDetectionHandler.h
  src/handlers/StateMachineHandler.cpp
  src/handlers/StateMachineHandler.h
  src/handlers/TagDetectionHandler.cpp
  src/handlers/TagDetectionHandler.h
  src/main.cpp
  src/states/ApproachingMarkerState.cpp
  src/states/IdleState.cpp
  src/states/SearchPatternState.cpp
  src/vision/aruco/TagDetector.cpp
Labels: cleanup, cameras, state-machine

#239 Update README and Git Extension Settings.
  .devcontainer/devcontainer.json
  README.md
Labels: documentation, cleanup

#240 Fix for ssh devcontainer
  .devcontainer/devcontainer.json
Labels: bug

#238 Repo Cleanup
  .devcontainer/devcontainer.json
  .github/workflows/deploy_autonomy.yml
  .github/workflows/tests.yml
  CMakeLists.txt
  README.md
  src/AutonomyConstants.h
  src/AutonomyLogging.cpp
Labels: enhancement, 1-Star, formatting, cleanup, dev-environment, logging

#241 Fix Local Time in Containers
  .devcontainer/devcontainer.json
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyLogging.cpp
Labels: bug, 1-Star, dev-environment

#243 Hotfix/#237
  src/vision/aruco/ArucoDetection.hpp
  src/vision/aruco/TagDetector.cpp
Labels: bug

#246 Fix Occasional Actions CMAKE Failure
  .github/workflows/deploy_autonomy.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
  CMakeLists.txt
Labels: bug, actions

#245 Fix RoveComm Overwriting of Doxygen Homepage
  Doxyfile
Labels: bug, documentation, 1-Star, formatting

#244 Alert Leads of Help Requests
  .github/workflows/help_request.yml
Labels: enhancement, 1-Star, actions

#247 README and Doxygen Updates
  Doxyfile
  README.md
  docs/Doxygen/resources/DoxygenLayout.xml
Labels: bug, documentation, enhancement, 1-Star, formatting, cleanup

#251 Fix Parallelize Loop Functionality of AutonomyThread
  src/interfaces/AutonomyThread.hpp
Labels: bug

#250 Auto Increment Software Versions
  .github/workflows/deploy_autonomy.yml
Labels: enhancement, 1-Star, actions

#257 [HOTFIX] Fix GitHub Actions
  .github/workflows/deploy_autonomy.yml
Labels: bug, 1-Star, actions
