Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-03, with the labels that each got.

#193 Write Search Pattern Unit Tests #191
  src/algorithms/SearchPattern.hpp
  src/util/GeospatialOperations.hpp
  tests/Unit/src/algorithms/SearchPattern.cc
Labels: 1-Star, unit tests

#194 Fixed StanleyController Unit Test UTM to GPS conversions.
  tests/Unit/src/algorithms/controllers/StanleyController.cc
Labels: bug

#195 Update Autonomy_Software and RoveComm_CPP Versions/Commit
  CMakeLists.txt
Labels: enhancement, 1-Star, rovecomm

#197 Update deploy_autonomy.yml
  .github/workflows/deploy_autonomy.yml
Labels: bug, 1-Star, actions

#198 Update deploy_autonomy.yml
  .github/workflows/deploy_autonomy.yml
Labels: bug, 1-Star, actions

#199 README Updates
  README.md
Labels: documentation, 1-Star, formatting, cleanup

#200 Move StateMachine States into h/cpp files
  src/handlers/StateMachineHandler.h
  src/states/ApproachingMarkerState.cpp
  src/states/ApproachingMarkerState.h
  src/states/ApproachingMarkerState.hpp
  src/states/ApproachingObjectState.cpp
  src/states/ApproachingObjectState.h
  src/states/ApproachingObjectState.hpp
  src/states/AvoidanceState.cpp
  src/states/AvoidanceState.h
  src/states/AvoidanceState.hpp
  src/states/IdleState.cpp
  src/states/IdleState.h
  src/states/IdleState.hpp
  src/states/NavigatingState.cpp
  src/states/NavigatingState.h
  src/states/NavigatingState.hpp
  src/states/ReversingState.cpp
  src/states/ReversingState.h
  src/states/ReversingState.hpp
  src/states/SearchPatternState.cpp
  src/states/SearchPatternState.h
  src/states/SearchPatternState.hpp
  src/states/StuckState.cpp
  src/states/StuckState.h
  src/states/StuckState.hpp
  src/states/VerifyingMarkerState.cpp
  src/states/VerifyingMarkerState.h
  src/states/VerifyingMarkerState.hpp
  src/states/VerifyingObjectState.cpp
  src/states/VerifyingObjectState.h
  src/states/VerifyingObjectState.hpp
Labels: bug, 2-Star, formatting

#201 Implement RoveComm Functionality for Drivers
  .devcontainer/devcontainer.json
  CMakeLists.txt
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/AutonomyGlobals.cpp
  src/AutonomyGlobals.h
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/MultimediaBoard.h
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/main.cpp
Labels: bug, enhancement, 2-Star, rovecomm

#202 Update RoveComm and Subscribe to NavBoard
  CMakeLists.txt
  src/drivers/NavigationBoard.cpp
  src/main.cpp
Labels: bug, 1-Star, rovecomm

#204 Add GPS Based Rover Velocity Calculation to NavBoard
  src/drivers/NavigationBoard.cpp
  src/drivers/NavigationBoard.h
  src/handlers/StateMachineHandler.h
  src/main.cpp
Labels: enhancement, 1-Star, cleanup

#205 ZEDCam Fusion Errors When Disabled.
  data/models/zed/.8501_timing_cache
  src/AutonomyConstants.h
  src/drivers/NavigationBoard.h
  src/main.cpp
  src/vision/cameras/ZEDCam.cpp
Labels: bug, 1-Star

#207 Integrate Autonomy with RoveComm and SIM
  .devcontainer/devcontainer.json
  CMakeLists.txt
  README.md
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/AutonomyLogging.cpp
  src/AutonomyLogging.h
  src/algorithms/DifferentialDrive.hpp
  src/algorithms/SearchPattern.hpp
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
  src/drivers/MultimediaBoard.cpp
  src/drivers/NavigationBoard.cpp
  src/handlers/StateMachineHandler.cpp
  src/handlers/StateMachineHandler.h
  src/handlers/WaypointHandler.cpp
  src/handlers/WaypointHandler.h
  src/interfaces/AutonomyThread.hpp
  src/interfaces/State.hpp
  src/main.cpp
  src/states/ApproachingMarkerState.cpp
  src/states/ApproachingMarkerState.h
  src/states/ApproachingObjectState.cpp
  src/states/ApproachingObjectState.h
  src/states/AvoidanceState.cpp
  src/states/AvoidanceState.h
  src/states/IdleState.cpp
  src/states/IdleState.h
  src/states/NavigatingState.cpp
  src/states/NavigatingState.h
  src/states/ReversingState.cpp
  src/states/ReversingState.h
  src/states/SearchPatternState.cpp
  src/states/SearchPatternState.h
  src/states/StuckState.cpp
  src/states/StuckState.h
  src/states/VerifyingMarkerState.cpp
  src/states/VerifyingMarkerState.h
  src/states/VerifyingObjectState.cpp
  src/states/VerifyingObjectState.h
  src/util/GeospatialOperations.hpp
  tests/Unit/src/algorithms/SearchPattern.cc
Labels: bug, 3-Star, cleanup, dev-environment, rovecomm

#208 Add RoveComm Logger
  CMakeLists.txt
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyGlobals.cpp
  src/AutonomyGlobals.h
  src/AutonomyLogging.cpp
  src/AutonomyLogging.h
  src/AutonomyNetworking.cpp
  src/AutonomyNetworking.h
  src/drivers/DriveBoard.cpp
  src/drivers/MultimediaBoard.cpp
  src/drivers/NavigationBoard.cpp
  src/handlers/StateMachineHandler.cpp
  src/handlers/WaypointHandler.cpp
  src/main.cpp
Labels: enhancement, 2-Star, formatting, rovecomm, logging

#209 Upgrade to Quill 3.7.0
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  tools/package-builders/quill/quill-amd64-pkg.sh
  tools/package-builders/quill/quill-arm64-pkg.sh
Labels: enhancement, 1-Star, docker, dev-environment, logging

#211 Use Auto-generated Container Names
  .devcontainer/devcontainer.json
Labels: dev-environment

#212 Upgrade BS::thread_pool to 4.0.1
  CMakeLists.txt
  external/threadpool/BSThreadPool.hpp
  external/threadpool/README.md
  src/interfaces/AutonomyThread.hpp
Labels: enhancement, 2-Star, dev-environment

#215 Update libedgetpu commit to an older working one.
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  tests/Unit/src/util/IPS.cc
  tools/action-runners/Dockerfile_Jammy
  tools/action-runners/Dockerfile_JetPack
  tools/action-runners/scripts/start.sh
  tools/package-builders/tensorflow/tensorflow-amd64-pkg.sh
  tools/package-builders/tensorflow/tensorflow-arm64-pkg.sh
Labels: bug, dev-environment

#216 Fix IPS Unit Test
  tests/Unit/src/util/IPS.cc
Labels: bug, unit tests

#217 Cleanup Includes
  external/threadpool/BSThreadPool.hpp
  src/interfaces/TensorflowTPU.hpp
  src/main.cpp
  src/util/vision/ArucoSamplesUtility.hpp
  src/util/vision/FetchContainers.hpp
  src/util/vision/YOLOModel.hpp
  src/vision/objects/DepthDetection.hpp
  src/vision/objects/ObjectDetector.h
  src/vision/objects/TensorflowObjectDetection.hpp
  tests/Unit/src/algorithms/controllers/PIDController.cc
Labels: documentation, cleanup

#219 Reimplement Valgrind
  .github/workflows/valgrind.yml
  README.md
  tools/valgrind/run_valgrind.sh
Labels: enhancement, 1-Star, actions

#220 Upgrade to Quill to v3.8.0
  .devcontainer/Dockerfile_Jammy
  .devcontainer/Dockerfile_JetPack
  tools/package-builders/quill/quill-amd64-pkg.sh
  tools/package-builders/quill/quill-arm64-pkg.sh
Labels: enhancement, 1-Star, docker, dev-environment, logging

#222 Add Setup and Clean Action Runners Steps
  .github/workflows/codeql.yml
  .github/workflows/deploy_autonomy.yml
  .github/workflows/deploy_docker.yml
  .github/workflows/tests.yml
  .github/workflows/valgrind.yml
Labels: enhancement, 1-Star, actions, cleanup

#225 Cleanup and Intellisense
  .devcontainer/devcontainer.json
  .gitignore
  .vscode/c_cpp_properties.json
  src/interfaces/AutonomyThread.hpp
Labels: bug, cleanup, dev-environment

#227 Fix ZEDCam freeze.
  src/vision/cameras/ZEDCam.cpp
Labels: bug, cameras
