Repository MissouriMRDT/Autonomy_Software, pull requests merged in 2024-02, with the labels that each got.

#172 Added controllers namespace to PIDController.
  src/algorithms/DifferentialDrive.hpp
  src/algorithms/controllers/PIDController.cpp
  src/algorithms/controllers/PIDController.h
  src/drivers/DriveBoard.cpp
  src/drivers/DriveBoard.h
Labels: bug, 1-Star, cleanup

#173 DriveBoard Class and `diffdrive` Namespace Cleanup
  src/AutonomyConstants.h
  src/algorithms/DifferentialDrive.hpp
  src/drivers/DriveBoard.cpp
Labels: 1-Star, cleanup

#174 Implement Waypoint Handler
  data/models/zed/.8501_timing_cache
  examples/vision/cameras/OpenZEDCam.hpp
  examples/vision/tagdetection/ArucoDetectionZED.hpp
  src/AutonomyGlobals.cpp
  src/AutonomyGlobals.h
  src/handlers/WaypointHandler.cpp
  src/handlers/WaypointHandler.h
  src/interfaces/Camera.hpp
  src/main.cpp
  src/util/GeospatialOperations.hpp
  src/vision/cameras/BasicCam.cpp
  src/vision/cameras/SIMCam.cpp
  src/vision/cameras/ZEDCam.cpp
  src/vision/cameras/ZEDCam.h
Labels: enhancement, 2-Star, cleanup

#175 Fix Incomplete Type Error With Structs.
  src/handlers/WaypointHandler.cpp
  src/handlers/WaypointHandler.h
  src/vision/cameras/ZEDCam.cpp
  src/vision/cameras/ZEDCam.h
Labels: bug, 1-Star

#177 Fix State Machine Inheritance Scope
  src/handlers/StateMachineHandler.h
Labels: bug, 1-Star, formatting, cleanup

#184 [HOTFIX] - File Existence Plugin
  .github/workflows/tests.yml
Labels: bug, enhancement, 1-Star, actions, dev-environment

#185 [HOTFIX] - GitHub Pages and Doxygen Actions
  .github/workflows/doxygen_generate.yml
Labels: bug, enhancement, 1-Star, actions, dev-environment

#186 [HOTFIX] - GitHub Artifacts Plugin
  .github/workflows/deploy_autonomy.yml
Labels: bug, documentation, 1-Star, actions, dev-environment

#182 Implement Feature Rich ASTAR Pathfinder
  CMakeLists.txt
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/algorithms/planners/AStar.cpp
  src/algorithms/planners/AStar.h
  src/algorithms/planners/README.md
  src/states/AvoidanceState.hpp
  src/util/planners/Nodes.hpp
Labels: enhancement, 2-Star

#188 Fix Random Failing Actions
  .github/workflows/tests.yml
Labels: bug, 1-Star, actions

#189 [HOTFIX] Missed inappropriate #include from AStar merge.
  src/algorithms/planners/AStar.cpp
Labels: cleanup

#187 Implement Feature Rich STANLEY Pathfollower
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/AutonomyConstants.h
  src/algorithms/controllers/StanleyController.cpp
  src/algorithms/controllers/StanleyController.h
  src/states/AvoidanceState.hpp
  tests/Unit/src/algorithms/controllers/StanleyController.cc
Labels: enhancement, 3-Star, unit tests

#190 Implement Search Pattern Algorithm (#158)
  data/Custom_Dictionaries/Autonomy-Dictionary.txt
  src/algorithms/SearchPattern.hpp
  src/states/SearchPatternState.hpp
Labels: enhancement

#192 [HOTFIX] Fix JetPack Build Architecture
  .github/workflows/deploy_docker.yml
Labels: bug, 1-Star, docker, actions, dev-environment
